import { naviGuide } from '../components/naviGuide.js';

export function challengeView(){
  document.querySelector('#app').innerHTML=`<div class="page">
    <div class="toolbar"><div><p class="eyebrow">演習</p><h1>演習に取り組む</h1><p class="lead">「図形を見分ける → 考え方 → 式 → 答え」の順に、じっくり確かめよう。</p></div><a class="btn btn-secondary" href="#home">島へ戻る</a></div>
    <section class="route-panel route-practice practice-hub section"><div class="route-panel-header"><div><p class="route-kicker">分かったことを使う時間</p><h2>10ステージで力をつける</h2><p>理解を深める体験のあとに、できる問題から始めて大丈夫です。</p></div><span class="route-number">演習</span></div><div class="practice-hub-actions"><a class="btn btn-primary" href="#stages">10ステージから選ぶ</a><a class="btn btn-secondary" href="#practice/0">ランダムで1問</a></div>${naviGuide('まずはできそうなステージを1つ選んで、最後までやってみよう。','thinking')}</section>
    <section class="section"><div class="section-heading"><div><p class="eyebrow">単元別に選ぶ</p><h2>演習の部屋</h2><p>苦手な内容や、もう一度取り組みたい内容を選べます。</p></div><a class="btn btn-secondary" href="#stages">10ステージ一覧</a></div><div class="mode-grid practice-room-grid"><a class="card mode-card" href="#practice/4"><p class="eyebrow">演習 01</p><h2>おうぎ形の部屋</h2><p>円の何分のいくつかを、おうぎ形として考える。</p></a><a class="card mode-card" href="#practice/7"><p class="eyebrow">演習 02</p><h2>引き算の部屋</h2><p>大きい図形から小さい図形を引く。</p></a><a class="card mode-card" href="#practice/8"><p class="eyebrow">演習 03</p><h2>組み合わせの部屋</h2><p>葉っぱ型・まがたま型などを分けて考える。</p></a><a class="card mode-card" href="#practice/10"><p class="eyebrow">演習 04</p><h2>総合の部屋</h2><p>図形の見方から式、答えまで挑戦。</p></a><a class="card mode-card" href="#practice/0"><p class="eyebrow">演習 05</p><h2>どんどんの部屋</h2><p>数値が変わるランダム問題に挑戦。</p></a></div></section>
    <section class="panel section"><div class="toolbar"><div><p class="eyebrow">つまずいたら</p><h2>もう一度、理解を深める</h2><p>ケーキショップやレスキューで、図を動かしながら確かめ直せます。</p></div><div class="actions"><a class="btn btn-secondary" href="#play/cake">ケーキショップ</a><a class="btn btn-secondary" href="#play/rescue">ずけいレスキュー</a></div></div></section>
  </div>`;
}
